= iced nREPL

https://github.com/nrepl/nREPL[nREPL] middleware to support https://github.com/liquidz/vim-iced[vim-iced].


image:https://github.com/liquidz/iced-nrepl/workflows/build/badge.svg["GitHub Actions for build workflow", link="https://github.com/liquidz/iced-nrepl/actions?query=workflow%3Abuild"]
image:https://github.com/liquidz/iced-nrepl/workflows/lint/badge.svg["GitHub Actions for lint workflow", link="https://github.com/liquidz/iced-nrepl/actions?query=workflow%3Alint"]
image:https://github.com/liquidz/iced-nrepl/workflows/dependencies/badge.svg["GitHub Actions for dependencies workflow", link="https://github.com/liquidz/iced-nrepl/actions?query=workflow%3Adependencies"]
image:https://codecov.io/gh/liquidz/iced-nrepl/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/liquidz/iced-nrepl"]
image:https://img.shields.io/clojars/v/iced-nrepl.svg["Clojars Project", link="https://clojars.org/iced-nrepl"]

== Ops

[cols="4*,a"]
|===
| Op name | Required | Optional | Return | Note

| iced-version
|
|
| `:version`
|

| iced-project-ns-list
|
|
| `:project-ns-list`
|

| iced-pseudo-ns-path
| `:ns`
|
| `:path`
|

| iced-set-indentation-rules
| `:rules`
| `:overwrite?`
|
| default indentation rule is `cljfmt.core/default-indents` +
If `:overwrite?` is If logical true, `cljfmt.core/default-indents` will not be used.

| iced-format-code-with-indents
| `:code`, `:alias-map`
|
| `:formatted`
|

| iced-calculate-indent-level
| `:code`, `:line-number`, `:alias-map`
|
| `:indent-level`, `:error` (if occurred)
| `:line-number` is zero-based

| iced-refactor-thread-first
| `:code`
|
| `:code`, `:error` (if occurred)
|

| iced-refactor-thread-last
| `:code`
|
| `:code`, `:error` (if occurred)
|

| iced-spec-check
| `:symbol`, `:num-tests`
|
| `:result`, `:num-tests`, `:error` (if errored), `:failed-input` (if errored)
| `:result` is "OK" or "NG" +
`:num-tests` must be positive integer

| iced-list-tapped
|
| `:max-depth`, `:max-list-length`, `:max-vector-length`, `:max-set-length`, `:max-string-length`
| `:tapped`, `:error` (if errored)
| `:tapped` is a map containing `:unique-id` and `:value` keys.

| iced-browse-tapped
| `keys`
| `:max-depth`, `:max-list-length`, `:max-vector-length`, `:max-set-length`, `:max-string-length`
| `:value`, `:error` (if errored)
| The first element of `keys` must be one of index number or unique-id.

| iced-fetch-tapped-children
| `keys`
|
| `:children`, `:error` (if errored)
|

| iced-complete-tapped
| `keys`
| `:max-depth`, `:max-list-length`, `:max-vector-length`, `:max-set-length`, `:max-string-length`
| `:complete`, `:error` (if errored)
|

| iced-delete-tapped
| `key`
|
| `:result`, `:error` (if errored)
| `key` must be one of index number or unique-id.

| iced-clear-tapped
|
|
| `:result`, `:error` (if errored)
|

|===

== License

Copyright © 2018-2020 https://twitter.com/uochan[Masashi Iizuka]

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
