= iced nREPL

https://github.com/nrepl/nREPL[nREPL] middleware to support https://github.com/liquidz/vim-iced[vim-iced].

image:https://img.shields.io/circleci/project/github/liquidz/iced-nrepl/master.svg["CircleCI", link="https://circleci.com/gh/liquidz/iced-nrepl"]
image:https://versions.deps.co/liquidz/iced-nrepl/status.svg["Dependencies Status", link="https://versions.deps.co/liquidz/iced-nrepl"]
image:https://codecov.io/gh/liquidz/iced-nrepl/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/liquidz/iced-nrepl"]
image:https://img.shields.io/clojars/v/iced-nrepl.svg["Clojars Project", link="https://clojars.org/iced-nrepl"]

== Ops

[cols="4*,a"]
|===
| Op name | Required | Optional | Return | Note

| iced-version
|
|
| `:version`
|

| iced-lint-file
| `:file`, `:env`, `:opt`
|
| `:lint-warnings`, `:error` (if occured)
| `:env` must be "clj" or "cljs" +
`:opt` is a option map for https://github.com/jonase/eastwood#usage[jonase/eastwood] such as `:linters`, `:exclute-linters` and so on.

| iced-project-ns-list
|
|
| `:project-ns-list`
|

| iced-set-indentation-rules
| `:rules`
| `:overwrite?`
|
| default indentation rule is `cljfmt.core/default-indents` +
If `:overwrite?` is If logical true, `cljfmt.core/default-indents` will not be used. +
https://github.com/clojure-emacs/cider-nrepl/pull/556[WILL DEPRECATE]

| iced-format-code-with-indents
| `:code`, `:alias-map`
|
| `:formatted`
| https://github.com/clojure-emacs/cider-nrepl/pull/556[WILL DEPRECATE]

| iced-calculate-indent-level
| `:code`, `:line-number`, `:alias-map`
|
| `:indent-level`, `:error` (if occured)
| `:line-number` is zero-based

| iced-refactor-thread-first
| `:code`
|
| `:code`, `:error` (if occured)
|

| iced-refactor-thread-last
| `:code`
|
| `:code`, `:error` (if occured)
|

| iced-spec-check
| `:symbol`, `:num-tests`
|
| `:result`, `:num-tests`, `:message` (if errored), `:fail` (if errored)
| `:result` is "OK" or "NG" +
`:num-tests` must be positive integer

|===

== License

Copyright © 2018-2019 https://twitter.com/uochan[Masashi Iizuka]

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
