= iced nREPL

https://github.com/nrepl/nREPL[nREPL] middleware to support https://github.com/liquidz/vim-iced[vim-iced].

image:https://versions.deps.co/liquidz/iced-nrepl/status.svg["Dependencies Status", link="https://versions.deps.co/liquidz/iced-nrepl"]
image:https://circleci.com/gh/liquidz/iced-nrepl.svg?style=svg["CircleCI", link="https://circleci.com/gh/liquidz/iced-nrepl"]
image:https://img.shields.io/clojars/v/iced-nrepl.svg["Clojars Project", link="https://clojars.org/iced-nrepl"]

== Ops

[cols="4*,a"]
|===
| Op name | Required | Optional | Return | Note

| iced-version
|
|
| `:version`
|

| lint-file
| `:file`, `:env`, `:linters`
|
| `:lint-warnings`, `:error` (if occured)
| `:env` must be "clj" or "cljs"

| grimoire
| `:platform`, `:ns`, `:symbol`
|
| `:content`, `:http-status` (if errored)
|

| related-namespaces
|
| `:ns`
| `:related-namespaces`
|

| ns-aliases
| `:env`, `:code`
|
| `:aliases`, `:error` (if occured)
| `:env` must be "clj" or "cljs" +
`:code` is `ns` form code

| set-indentation-rules
| `:rules`
|
|
| default indentation rule is `cljfmt.core/default-indents`

| format-code-with-indents
| `:code`, `:alias-map`
|
| `:formatted`
|

| refactor-thread-first
| `:code`
|
| `:code`, `:error` (if occured)
|

| refactor-thread-last
| `:code`
|
| `:code`, `:error` (if occured)
|

| spec-check
| `:symbol`, `:num-tests`
|
| `:result`, `:num-tests`, `:message` (if errored), `:fail` (if errored)
| `:result` is "OK" or "NG" +
`:num-tests` must be positive integer

|===

== License

Copyright © 2018 https://twitter.com/uochan[Masashi Iizuka]

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
