name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: ['8', '11', '17']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - run: |
          java -version
          clojure --version
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: clojure-m2-${{ hashFiles('deps.edn') }}
      - name: Run tests
        run: make test
